openapi: 3.0.0
info:
  title: User Management
  description: |-
    This is all about User Management API

    | Syntax      | Description |
    | ----------- | ----------- |
    | Header      | Title       |
    | Paragraph   | Text        |
  version: 1.0.0
servers:
  - url: 'https://test'
    description: Dev server
paths:
  '/services/data/{version}/subjects/user/{id}':
    get:
      tags:
        - User Management
      summary: View User Preferences
      description: |-
        This is all about User Management API

        | Name        | Description |
        | ----------- | ----------- |
        | Header      | Title       |
        | Paragraph   | Text        |

        User management describes the ability for administrators to manage user access to various IT resources like systems, devices, applications, storage systems, networks, SaaS services, and more. ... User management enables admins to control user access and on-board and off-board users to and from IT resources
      parameters:
        - name: version
          in: path
          description: Version Number
          required: true
          style: simple
          explode: false
          schema:
            type: integer
        - name: id
          in: path
          description: 18 Digit Alphanumeric Unique Identifier of the User to limit references in the backend.
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: fields
          in: query
          description: Different fields names
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/View'
              examples:
                example-1: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/View'
      security:
        - Bearer: []
      operationId: ''
    patch:
      tags:
        - User Management
      summary: Update User Preferences
      description: "Specify the fields you want to update within the body of the request and use the PATCH method of the resource. Refer  <a href=\"https://bp365.sharepoint.com/sites/IdentityAccessManagementIAMHub/SitePages/Consumer_Idp_Service.aspx#service-end-points\">Customer & Consumer Identity</a> for latest version number of these API's"
      parameters:
        - name: version
          in: path
          description: Version Number
          required: true
          style: simple
          explode: false
          schema:
            type: integer
        - name: id
          in: path
          description: 18 Digit Alphanumeric Unique Identifier of the User to limit references in the backend.
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserPreferences'
          application/xml:
            schema:
              $ref: '#/components/schemas/UpdateUserPreferences'
      responses:
        '200':
          description: Successful response
          content: {}
      security:
        - Bearer: []
components:
  schemas:
    View:
      title: View User Consent
      type: object
      properties:
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/attributes'
        FirstName:
          type: string
          example: John
          description: first name of the customer
        Email:
          type: string
          example: john.smith@example.com
        Phone:
          type: integer
          example: 15417543010
    UpdateUserPreferences:
      title: Update User Preferences
      type: object
      properties:
        Phone:
          type: integer
          example: 15417543010
      description: 'User management describes the ability for administrators to manage user access to various IT resources like systems, devices, applications, storage systems, networks, SaaS services, and more. ... User management enables admins to control user access and on-board and off-board users to and from IT resources'
    attributes:
      title: attribute
      type: object
      properties:
        url:
          type: string
          example: /services/data/v48.0/sobjects/User/0050E000000RlEQQA0
          description: |
            url
      x-examples:
        example-1: {}
      description: 'User management describes the ability for administrators to manage user access to various IT resources like systems, devices, applications, storage systems, networks, SaaS services, and more. ... User management enables admins to control user access and on-board and off-board users to and from IT resources'
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
